services:
  - type: web
    plan: free
    name: Helloralender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app & python3 main.py
    repo: https://github.com/Amanraj654/Helloralender.git      
    branch: main
    envVars:
      - key: TOKEN 
        sync: false
      - key: ID 
        sync: false
      - key: HASH 
        sync: false
      - key: STRING 
        sync: false
    autoDeploy: false 
